$(document).ready(function(){
  $('#photo1').click(function(){
    $('#photo1').animate({height: "17vw"  ,width: "17vw" ,top: "-2vh", left:"20vw"});
    $('#photo2').animate({height: "3.5vw" ,width: "3.5vw" ,top: "6vh" , left:"-28.1vw"});
    $('#photo3').animate({height: "3.5vw" ,width: "3.5vw" ,top: "16vh", left:"-45.7vw"});
    $('#photo4').animate({height: "3.5vw" ,width: "3.5vw" ,top: "26vh", left:"-63.3vw"});
    $('#photo5').animate({height: "3.5vw" ,width: "3.5vw" ,top: "36vh", left:"-80.9vw"});
    $('.member p').hide();
    $('#info1').show("slow");
    $('#info2').slideUp();
    $('#info3').slideUp();
    $('#info4').slideUp();
    $('#info5').slideUp();
    $('.btn').show();
    $('.list').css("background-color","#F2F2F2");
    $('.page2').show("slow"); 
  });
  $('#photo2').click(function(){
    $('#photo2').animate({height: "17vw"  ,width: "17vw" ,top: "-2vh", left:"2.4vw"});
    $('#photo1').animate({height: "3.5vw" ,width: "3.5vw" ,top: "-4vh", left:"-10.5vw"});
    $('#photo3').animate({height: "3.5vw" ,width: "3.5vw" ,top: "16vh", left:"-45.7vw"});
    $('#photo4').animate({height: "3.5vw" ,width: "3.5vw" ,top: "26vh", left:"-63.3vw"});
    $('#photo5').animate({height: "3.5vw" ,width: "3.5vw" ,top: "36vh", left:"-80.9vw"});
    $('.member p').hide();
    $('#info1').slideUp();
    $('#info2').show("slow");
    $('#info3').slideUp();
    $('#info4').slideUp();
    $('#info5').slideUp();
    $('.btn').show(); 
    $('.list').css("background-color","#F2F2F2");
    $('.page2').show("slow"); 
  });
  $('#photo3').click(function(){
    $('#photo3').animate({height: "17vw"  ,width: "17vw" ,top: "-2vh", left:"-15.2vw"});
    $('#photo1').animate({height: "3.5vw" ,width: "3.5vw" ,top: "-4vh",left:"-10.5vw"});
    $('#photo2').animate({height: "3.5vw" ,width: "3.5vw" ,top: "6vh",left:"-28.1vw"});
    $('#photo4').animate({height: "3.5vw" ,width: "3.5vw" ,top: "26vh",left:"-63.3vw"});
    $('#photo5').animate({height: "3.5vw" ,width: "3.5vw" ,top: "36vh",left:"-80.9vw"});
    $('.member p').hide();
    $('#info1').slideUp();
    $('#info2').slideUp();
    $('#info3').show("slow");
    $('#info4').slideUp();
    $('#info5').slideUp();
    $('.btn').show(); 
    $('.list').css("background-color","#F2F2F2");
    $('.page2').show("slow"); 
  });
  $('#photo4').click(function(){
    $('#photo4').animate({height: "17vw"  ,width: "17vw" ,top: "-2vh", left:"-32.8vw"});
    $('#photo1').animate({height: "3.5vw" ,width: "3.5vw" ,top: "-4vh", left:"-10.5vw"});
    $('#photo2').animate({height: "3.5vw" ,width: "3.5vw" ,top: "6vh", left:"-28.1vw"});
    $('#photo3').animate({height: "3.5vw" ,width: "3.5vw" ,top: "16vh", left:"-45.7vw"});
    $('#photo5').animate({height: "3.5vw" ,width: "3.5vw" ,top: "36vh", left:"-80.9vw"});
    $('.member p').hide();
    $('#info1').slideUp();
    $('#info2').slideUp();
    $('#info3').slideUp();
    $('#info4').show("slow");
    $('#info5').slideUp();
    $('.btn').show(); 
    $('.list').css("background-color","#F2F2F2");
    $('.page2').show("slow"); 
  });
  $('#photo5').click(function(){
    $('#photo5').animate({height: "17vw"  ,width: "17vw" ,top: "-2vh", left:"-50.4vw"});
    $('#photo1').animate({height: "3.5vw" ,width: "3.5vw" ,top: "-4vh", left:"-10.5vw"});
    $('#photo2').animate({height: "3.5vw" ,width: "3.5vw" ,top: "6vh", left:"-28.1vw"});
    $('#photo3').animate({height: "3.5vw" ,width: "3.5vw" ,top: "16vh", left:"-45.7vw"});
    $('#photo4').animate({height: "3.5vw" ,width: "3.5vw" ,top: "26vh", left:"-63.3vw"});
    $('.member p').hide();
    $('#info1').slideUp();
    $('#info2').slideUp();
    $('#info3').slideUp();
    $('#info4').slideUp();
    $('#info5').show("slow");
    $('.btn').show(); 
    $('.list').css("background-color","#F2F2F2");
    $('.page2').show("slow"); 
  });
  $('.btn').click(function(){
    $('#photo1').animate({height: "11vw" , width: "11vw", top: "0", left:"0"});
    $('#photo2').animate({height: "11vw" , width: "11vw", top: "0", left:"0"});
    $('#photo3').animate({height: "11vw" , width: "11vw", top: "0", left:"0"});
    $('#photo4').animate({height: "11vw" , width: "11vw", top: "0", left:"0"});
    $('#photo5').animate({height: "11vw" , width: "11vw", top: "0", left:"0"});
    $('.member p').show(); 
    $('#info1').slideUp();
    $('#info2').slideUp();
    $('#info3').slideUp();
    $('#info4').slideUp();
    $('#info5').slideUp();
    $('.btn').hide();
    $('.list').css("background-color","#F4C70B");
    $('.page2').hide();
  });
});
